spring:
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: localhost
  mvc:
    hiddenmethod:
      filter:
        enabled: true
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?characterEncoding=utf8
    username: chat
    password: chat
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

# server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: false
      force-request: false
      force-response: false

---
# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml
---
